services:
  mongodb:
    image: mongo:latest
    ports:
      - "17017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  mongo-seed:
    image: mongo:latest
    volumes:
      - ./mongodb_dump:/mongodb_dump
    depends_on:
      - mongodb
    command:
      [
        "/bin/bash",
        "-c",
        "sleep 10 && mongosh 'mongodb://root:example@mongodb:27017/art_gallery?authSource=admin' /mongodb_dump/art_gallery/dump.js",
      ]

volumes:
  mongodb_data:
